In [59]:
import numpy as np
import pandas as pd

In [60]:
cars = pd.read_csv('quikr_car.csv')

In [61]:
cars

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [62]:
cars.shape

(892, 6)

In [63]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

### Performing Data Cleaning

- year column has invalid data
- year data type is object, have to change in int
- price column has value 'Ask For Price'.
- price column is object
- In price column, we have to remove ','.
- kms column has value: 'nan', 'price'
- in kms column, we have to remove 'kms' unit and ','.
- column kms is object.
- Fuel_type column has 'nan' values
- Keep first 3 words of name columns

In [64]:
cars['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [65]:
cars['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [66]:
cars['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [67]:
cars['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [68]:
#Cleaning year column.
cars = cars[cars['year'].str.isnumeric()]

In [69]:
cars['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

In [70]:
cars['year']= cars['year'].astype('int32')

C:\Users\jeeva\AppData\Local\Temp\ipykernel_17676\741739624.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cars['year']= cars['year'].astype('int32')

In [114]:
cars['year'].head()

0    2007
1    2006
2    2014
3    2014
4    2012
Name: year, dtype: int32

In [71]:
#Cleaning Price column

In [72]:
cars = cars[cars['Price'] != 'Ask For Price']

In [73]:
cars['Price']= cars['Price'].str.replace(',','')

In [74]:
cars['Price'] = cars['Price'].astype('int')

In [75]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [76]:
#cleaning kms_driven
cars['kms_driven'] = cars['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [77]:
cars = cars[cars['kms_driven'] != 'Petrol']

In [78]:
cars['kms_driven'] = cars['kms_driven'].astype('int')

In [79]:
#Cleaning fuel_type
cars = cars[~cars['fuel_type'].isna()]

In [80]:
#cleaning name column
cars['name'] = cars['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [81]:
cars.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [82]:
cars.reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [83]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32
 3   Price       816 non-null    int32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [84]:
cars.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

- We can see that 25% - 75% are under 5 lakhs unders Price column. But in the max value is directly 85 lakhs. Means it clearly an outliear. We have to remove that
- There is one car that has price 85 lakh.

In [85]:
cars = cars[cars['Price'] < 6e6].reset_index(drop=True)

In [86]:
cars

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [87]:
#Saving the new Data
cars.to_csv('cleaned_cars.csv')

### Creating Model

In [88]:
#Splitting input and output columns
X = cars.drop(columns='Price')
y = cars['Price']

In [89]:
X #input

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [90]:
y #ouput

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

#### Performing Train-Test Split

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [93]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [94]:
ohe = OneHotEncoder()
ohe.fit(X_train[['name','company','fuel_type']])

OneHotEncoder()

### Creating a column transformer to transform categorical columns

In [95]:
from sklearn.compose import make_column_transformer

In [96]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_,handle_unknown="ignore"),['name','company','fuel_type']),
                                    remainder='passthrough')

### Linear Regression Model

In [97]:
lr = LinearRegression()

### Making a pipeline

In [98]:
from sklearn.pipeline import make_pipeline

In [99]:
pipe = make_pipeline(column_trans,lr)

### Fitting the model

In [100]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1 xDrive20d',
       'Chevrolet Beat', 'Chevrolet Beat Diesel', 'Chevrolet Beat LS'...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Mahindra',
       'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan', 'Renault',
       'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

### Predict the outputs

In [101]:
y_pred=pipe.predict(X_test)

In [102]:
y_pred

array([ 3.32814807e+05,  3.41015192e+05,  2.96287131e+05,  8.69618325e+04,
        3.92073459e+05,  3.63590698e+05,  2.45041787e+05,  6.76879365e+05,
        4.80215741e+05,  3.59667030e+05,  1.29901497e+05,  3.12118955e+05,
        3.03912165e+05,  4.28658443e+05,  1.26137185e+05,  1.91204225e+05,
        1.66058776e+05,  2.83361348e+05,  3.32546356e+05,  1.54680137e+05,
        4.33592269e+05,  2.39073589e+05,  6.45596133e+05,  2.55014823e+05,
        4.25810087e+05,  3.82251109e+05,  3.53744055e+05,  7.18279931e+05,
        4.84131414e+05,  3.40912948e+05, -1.92570006e+04,  4.07867909e+05,
        5.35017745e+05,  4.30116801e+05, -3.13082644e+02,  1.82453450e+05,
        5.39846545e+05,  1.31521555e+05,  1.87260979e+05,  3.37646898e+05,
        1.13015853e+05,  4.50542661e+05,  3.30970008e+05,  2.44890976e+05,
        1.10967346e+05,  2.90162274e+05,  2.48855544e+05,  6.32855298e+05,
        2.94183321e+05,  1.07306887e+05,  3.65766652e+05,  8.53719908e+04,
        3.69120449e+05,  4.75754329e+05,  1.07148397e+06,  1.74787623e+05,
        5.86947914e+05,  2.31578948e+05,  3.10489578e+05,  2.46890024e+05,
        1.60530392e+05,  3.69197087e+05, -1.00631060e+05,  2.63239284e+05,
        3.11558227e+05,  3.54703408e+05,  3.31333709e+05,  7.68237691e+04,
        5.01279781e+05,  2.61969813e+05,  1.91204225e+05,  6.28401959e+05,
        3.74347115e+05,  4.65579422e+05,  1.57116834e+05,  5.78767259e+05,
        1.97459305e+05,  4.18054867e+05,  5.85220316e+05,  3.88964796e+05,
        2.63512870e+04,  3.06806266e+05,  8.17255577e+04,  4.87943654e+05,
        1.38523105e+05,  1.74618837e+06,  2.72637857e+05,  3.76365399e+05,
        2.36219322e+05,  2.95198393e+05,  4.08875898e+05,  5.48420158e+05,
        4.32410067e+05,  3.09720516e+05,  4.11820752e+04,  3.63876416e+05,
        2.59845934e+05,  5.87331749e+05,  6.02299975e+05,  4.23575226e+05,
        6.90085679e+05,  8.83663147e+04,  6.04479742e+05,  4.58456336e+05,
        2.65056105e+04,  3.42451891e+05,  7.93849391e+04,  4.05822569e+05,
        1.56971967e+05,  8.95888076e+04,  8.90790894e+04,  3.33063621e+05,
        2.43812198e+05,  5.37896498e+05,  1.09883634e+06,  3.54703408e+05,
        2.26213798e+05,  1.72844103e+05,  3.87201566e+05,  5.22616771e+05,
        5.60942767e+05,  6.07382449e+05,  6.04401255e+05,  4.01104828e+05,
        1.54938345e+06,  3.72926019e+05,  6.61019433e+05,  2.71663810e+05,
        4.21951464e+05,  3.67543555e+05,  5.94130355e+05,  4.30960214e+05,
        2.06206801e+05, -1.71469249e+04,  4.16419271e+05,  4.58194370e+05,
        3.09458179e+05,  6.00030723e+05,  1.03967415e+05,  2.05143907e+05,
        3.98721140e+05,  5.83833418e+04,  5.11906874e+04,  5.38892774e+05,
        4.79554215e+05,  5.18525863e+05,  2.58916013e+05,  4.37468414e+05,
        4.86828914e+05,  5.40161754e+05,  8.10485470e+05,  6.54980678e+05,
        8.50981149e+05,  2.65281382e+05,  3.65766652e+05,  3.24794033e+05,
        2.36734542e+05,  3.94236368e+05,  2.09734756e+05,  2.20027054e+06,
        2.89986542e+05,  2.31831511e+05,  8.82613475e+04])

### Checking R2 Score

In [103]:
r2_score(y_test,y_pred)

0.6223951783688126

### Finding the model with a random state of TrainTestSplit where the model was found to give maximum r2_score

- Creating a model in a loop and checking the maximum r2 score

In [104]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [105]:
np.argmax(scores)

302

In [106]:
scores[np.argmax(scores)]

0.9002207388529742

In [107]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([430799.32559015])

### The best model is found at a certain random state

In [108]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.9002207388529742

### import pickle

In [109]:
import pickle

In [110]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [111]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([456045.38996716])

In [112]:
cars.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [113]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Hyundai Grand i10','Hyundai',2014,28000,'Petrol']).reshape(1,5)))

array([299651.5104935])